micronaut:
  application:
    name: authenticationService
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
netty:
  default:
    allocator:
      max-order: 3
